spring:
  datasource:
    url: jdbc:h2:mem:salesystem
    username: sa
    password: sa
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2_console
  jpa:
    show-sql: true
    properties:
     hibernate:
      jdbc:
       lob:
        non_contextual_creation: true
    hibernate:
      ddl-auto: none
      cashe:
        use_second_level_cache: true
        use_query_cache: false
        factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 8050

